create table if not exists public.holdings (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid(),
    symbol text not null,
    market text not null check (market in ('KR', 'US')),
    name text not null,
    quantity numeric not null,
    avg_price numeric not null,
    currency text not null default '₩',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique(user_id, symbol, market)
);

create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid(),
    symbol text not null,
    market text not null check (market in ('KR', 'US')),
    tx_type text not null check (tx_type in ('BUY', 'SELL')),
    quantity numeric not null,
    price numeric not null,
    currency text not null,
    memo text,
    tx_date timestamptz not null default timezone('utc', now())
);

create table if not exists public.watchlist (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid(),
    symbol text not null,
    market text not null check (market in ('KR', 'US')),
    name text not null,
    added_at timestamptz not null default timezone('utc', now()),
    unique(user_id, symbol, market)
);

create table if not exists public.signal_cache (
    symbol text not null,
    market text not null check (market in ('KR', 'US')),
    signal_level text not null check (signal_level in ('GREEN', 'YELLOW', 'RED')),
    signal_score numeric not null,
    is_capitulation boolean not null default false,
    details_json jsonb,
    computed_at timestamptz not null default timezone('utc', now()),
    primary key (symbol, market)
);

create table if not exists public.user_settings (
    user_id uuid not null default auth.uid(),
    key text not null,
    value text not null,
    primary key (user_id, key)
);

create index if not exists idx_transactions_user_date
    on public.transactions (user_id, tx_date desc);

create index if not exists idx_watchlist_user_market
    on public.watchlist (user_id, market);

create index if not exists idx_signal_cache_computed_at
    on public.signal_cache (computed_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists holdings_set_updated_at on public.holdings;
create trigger holdings_set_updated_at
before update on public.holdings
for each row
execute function public.set_updated_at();

alter table public.holdings enable row level security;
alter table public.transactions enable row level security;
alter table public.watchlist enable row level security;
alter table public.signal_cache enable row level security;
alter table public.user_settings enable row level security;

drop policy if exists "Users manage own holdings" on public.holdings;
create policy "Users manage own holdings"
on public.holdings
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own transactions" on public.transactions;
create policy "Users manage own transactions"
on public.transactions
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own watchlist" on public.watchlist;
create policy "Users manage own watchlist"
on public.watchlist
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own settings" on public.user_settings;
create policy "Users manage own settings"
on public.user_settings
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Signals readable by all clients" on public.signal_cache;
create policy "Signals readable by all clients"
on public.signal_cache
for select
using (true);
